// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptCertificate(arg1, arg2, arg3) {
  return window['go']['app']['App']['AcceptCertificate'](arg1, arg2, arg3);
}

export function AddAccount(arg1) {
  return window['go']['app']['App']['AddAccount'](arg1);
}

export function AddContact(arg1, arg2) {
  return window['go']['app']['App']['AddContact'](arg1, arg2);
}

export function AddContactSource(arg1) {
  return window['go']['app']['App']['AddContactSource'](arg1);
}

export function AddImageAllowlist(arg1, arg2) {
  return window['go']['app']['App']['AddImageAllowlist'](arg1, arg2);
}

export function AddMicrosoftSharedMailbox(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddMicrosoftSharedMailbox'](arg1, arg2, arg3);
}

export function AddPGPKeyServer(arg1) {
  return window['go']['app']['App']['AddPGPKeyServer'](arg1);
}

export function AddSpellcheckCustomWord(arg1) {
  return window['go']['app']['App']['AddSpellcheckCustomWord'](arg1);
}

export function Archive(arg1) {
  return window['go']['app']['App']['Archive'](arg1);
}

export function ArchiveWithUndo(arg1) {
  return window['go']['app']['App']['ArchiveWithUndo'](arg1);
}

export function BroadcastThemeChange(arg1) {
  return window['go']['app']['App']['BroadcastThemeChange'](arg1);
}

export function Calendar_AddCalDAVSource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['Calendar_AddCalDAVSource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Calendar_AddGoogleSource(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Calendar_AddGoogleSource'](arg1, arg2, arg3, arg4);
}

export function Calendar_AddLocalCalendar(arg1, arg2, arg3) {
  return window['go']['app']['App']['Calendar_AddLocalCalendar'](arg1, arg2, arg3);
}

export function Calendar_AddLocalSource(arg1) {
  return window['go']['app']['App']['Calendar_AddLocalSource'](arg1);
}

export function Calendar_AddMicrosoftSource(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Calendar_AddMicrosoftSource'](arg1, arg2, arg3, arg4);
}

export function Calendar_CreateEvent(arg1) {
  return window['go']['app']['App']['Calendar_CreateEvent'](arg1);
}

export function Calendar_DeleteCalendar(arg1) {
  return window['go']['app']['App']['Calendar_DeleteCalendar'](arg1);
}

export function Calendar_DeleteEvent(arg1, arg2) {
  return window['go']['app']['App']['Calendar_DeleteEvent'](arg1, arg2);
}

export function Calendar_DeleteSource(arg1) {
  return window['go']['app']['App']['Calendar_DeleteSource'](arg1);
}

export function Calendar_DismissAlarm(arg1) {
  return window['go']['app']['App']['Calendar_DismissAlarm'](arg1);
}

export function Calendar_ForceSyncSource(arg1) {
  return window['go']['app']['App']['Calendar_ForceSyncSource'](arg1);
}

export function Calendar_GetEvent(arg1) {
  return window['go']['app']['App']['Calendar_GetEvent'](arg1);
}

export function Calendar_GrantCalendarAccess(arg1, arg2, arg3) {
  return window['go']['app']['App']['Calendar_GrantCalendarAccess'](arg1, arg2, arg3);
}

export function Calendar_ListCalendars(arg1) {
  return window['go']['app']['App']['Calendar_ListCalendars'](arg1);
}

export function Calendar_ListEventsInRange(arg1, arg2, arg3) {
  return window['go']['app']['App']['Calendar_ListEventsInRange'](arg1, arg2, arg3);
}

export function Calendar_ListGoogleCalendarsForAccount(arg1) {
  return window['go']['app']['App']['Calendar_ListGoogleCalendarsForAccount'](arg1);
}

export function Calendar_ListMicrosoftCalendarsForAccount(arg1) {
  return window['go']['app']['App']['Calendar_ListMicrosoftCalendarsForAccount'](arg1);
}

export function Calendar_ListSources() {
  return window['go']['app']['App']['Calendar_ListSources']();
}

export function Calendar_LogFrontend(arg1, arg2) {
  return window['go']['app']['App']['Calendar_LogFrontend'](arg1, arg2);
}

export function Calendar_OpenURL(arg1) {
  return window['go']['app']['App']['Calendar_OpenURL'](arg1);
}

export function Calendar_QueryFreeBusy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Calendar_QueryFreeBusy'](arg1, arg2, arg3, arg4);
}

export function Calendar_RenameSource(arg1, arg2) {
  return window['go']['app']['App']['Calendar_RenameSource'](arg1, arg2);
}

export function Calendar_ReprobeCalDAVOrganizerIdentities(arg1) {
  return window['go']['app']['App']['Calendar_ReprobeCalDAVOrganizerIdentities'](arg1);
}

export function Calendar_SearchContacts(arg1, arg2) {
  return window['go']['app']['App']['Calendar_SearchContacts'](arg1, arg2);
}

export function Calendar_SetCalendarColor(arg1, arg2) {
  return window['go']['app']['App']['Calendar_SetCalendarColor'](arg1, arg2);
}

export function Calendar_SetCalendarVisible(arg1, arg2) {
  return window['go']['app']['App']['Calendar_SetCalendarVisible'](arg1, arg2);
}

export function Calendar_SetDisplayTimezone(arg1) {
  return window['go']['app']['App']['Calendar_SetDisplayTimezone'](arg1);
}

export function Calendar_SetOrganizerIdentity(arg1, arg2) {
  return window['go']['app']['App']['Calendar_SetOrganizerIdentity'](arg1, arg2);
}

export function Calendar_SetSyncInterval(arg1, arg2) {
  return window['go']['app']['App']['Calendar_SetSyncInterval'](arg1, arg2);
}

export function Calendar_SyncAllSources() {
  return window['go']['app']['App']['Calendar_SyncAllSources']();
}

export function Calendar_SyncSource(arg1) {
  return window['go']['app']['App']['Calendar_SyncSource'](arg1);
}

export function Calendar_UpdateEvent(arg1, arg2) {
  return window['go']['app']['App']['Calendar_UpdateEvent'](arg1, arg2);
}

export function Calendar_UpdateMyAttendeeStatus(arg1, arg2, arg3) {
  return window['go']['app']['App']['Calendar_UpdateMyAttendeeStatus'](arg1, arg2, arg3);
}

export function CanUndo() {
  return window['go']['app']['App']['CanUndo']();
}

export function CancelAccountSync(arg1) {
  return window['go']['app']['App']['CancelAccountSync'](arg1);
}

export function CancelAllSyncs() {
  return window['go']['app']['App']['CancelAllSyncs']();
}

export function CancelContactSourceOAuthFlow() {
  return window['go']['app']['App']['CancelContactSourceOAuthFlow']();
}

export function CancelFolderSync(arg1, arg2) {
  return window['go']['app']['App']['CancelFolderSync'](arg1, arg2);
}

export function CancelOAuthFlow() {
  return window['go']['app']['App']['CancelOAuthFlow']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckRecipientCerts(arg1) {
  return window['go']['app']['App']['CheckRecipientCerts'](arg1);
}

export function CheckRecipientPGPKeys(arg1) {
  return window['go']['app']['App']['CheckRecipientPGPKeys'](arg1);
}

export function ClearOAuthCreds(arg1) {
  return window['go']['app']['App']['ClearOAuthCreds'](arg1);
}

export function CloseWindow() {
  return window['go']['app']['App']['CloseWindow']();
}

export function CompleteContactSourceOAuthSetup(arg1, arg2) {
  return window['go']['app']['App']['CompleteContactSourceOAuthSetup'](arg1, arg2);
}

export function CompleteCustomOAuthAccountSetup(arg1) {
  return window['go']['app']['App']['CompleteCustomOAuthAccountSetup'](arg1);
}

export function CompleteOAuthAccountSetup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CompleteOAuthAccountSetup'](arg1, arg2, arg3, arg4, arg5);
}

export function Contacts_CancelSourceAuthorization() {
  return window['go']['app']['App']['Contacts_CancelSourceAuthorization']();
}

export function Contacts_CreateContact(arg1) {
  return window['go']['app']['App']['Contacts_CreateContact'](arg1);
}

export function Contacts_DeleteLocalContact(arg1) {
  return window['go']['app']['App']['Contacts_DeleteLocalContact'](arg1);
}

export function Contacts_EnableWriteAccess(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Contacts_EnableWriteAccess'](arg1, arg2, arg3, arg4);
}

export function Contacts_GetContactDetail(arg1) {
  return window['go']['app']['App']['Contacts_GetContactDetail'](arg1);
}

export function Contacts_LinkAccountSource(arg1, arg2, arg3) {
  return window['go']['app']['App']['Contacts_LinkAccountSource'](arg1, arg2, arg3);
}

export function Contacts_ListAddressbooks(arg1) {
  return window['go']['app']['App']['Contacts_ListAddressbooks'](arg1);
}

export function Contacts_ListContactsForBrowse(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Contacts_ListContactsForBrowse'](arg1, arg2, arg3, arg4);
}

export function Contacts_ListSources() {
  return window['go']['app']['App']['Contacts_ListSources']();
}

export function Contacts_ReauthorizeSource(arg1) {
  return window['go']['app']['App']['Contacts_ReauthorizeSource'](arg1);
}

export function Contacts_ResizeContactPhoto(arg1) {
  return window['go']['app']['App']['Contacts_ResizeContactPhoto'](arg1);
}

export function Contacts_SyncAllSources() {
  return window['go']['app']['App']['Contacts_SyncAllSources']();
}

export function Contacts_SyncSource(arg1) {
  return window['go']['app']['App']['Contacts_SyncSource'](arg1);
}

export function Contacts_UpdateContact(arg1, arg2) {
  return window['go']['app']['App']['Contacts_UpdateContact'](arg1, arg2);
}

export function CopyToFolder(arg1, arg2) {
  return window['go']['app']['App']['CopyToFolder'](arg1, arg2);
}

export function CreateIdentity(arg1, arg2) {
  return window['go']['app']['App']['CreateIdentity'](arg1, arg2);
}

export function DeleteContact(arg1) {
  return window['go']['app']['App']['DeleteContact'](arg1);
}

export function DeleteContactSource(arg1) {
  return window['go']['app']['App']['DeleteContactSource'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['app']['App']['DeleteDraft'](arg1);
}

export function DeleteIdentity(arg1) {
  return window['go']['app']['App']['DeleteIdentity'](arg1);
}

export function DeleteLocalMessages(arg1) {
  return window['go']['app']['App']['DeleteLocalMessages'](arg1);
}

export function DeletePGPKey(arg1) {
  return window['go']['app']['App']['DeletePGPKey'](arg1);
}

export function DeletePGPSenderKey(arg1) {
  return window['go']['app']['App']['DeletePGPSenderKey'](arg1);
}

export function DeletePermanently(arg1) {
  return window['go']['app']['App']['DeletePermanently'](arg1);
}

export function DeleteSMIMECertificate(arg1) {
  return window['go']['app']['App']['DeleteSMIMECertificate'](arg1);
}

export function DeleteSenderCert(arg1) {
  return window['go']['app']['App']['DeleteSenderCert'](arg1);
}

export function DiscoverCardDAVAddressbooks(arg1, arg2, arg3) {
  return window['go']['app']['App']['DiscoverCardDAVAddressbooks'](arg1, arg2, arg3);
}

export function DiscoverCardDAVAddressbooksOAuth(arg1, arg2) {
  return window['go']['app']['App']['DiscoverCardDAVAddressbooksOAuth'](arg1, arg2);
}

export function DiscoverOAuthProvider(arg1) {
  return window['go']['app']['App']['DiscoverOAuthProvider'](arg1);
}

export function DownloadAttachment(arg1, arg2) {
  return window['go']['app']['App']['DownloadAttachment'](arg1, arg2);
}

export function DownloadEncryptedAttachment(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadEncryptedAttachment'](arg1, arg2, arg3);
}

export function EmptyTrash(arg1, arg2) {
  return window['go']['app']['App']['EmptyTrash'](arg1, arg2);
}

export function EmptyUnifiedTrash() {
  return window['go']['app']['App']['EmptyUnifiedTrash']();
}

export function FetchMessageBody(arg1) {
  return window['go']['app']['App']['FetchMessageBody'](arg1);
}

export function FetchServerMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchServerMessage'](arg1, arg2, arg3);
}

export function FindLocalMessageIDs(arg1, arg2, arg3) {
  return window['go']['app']['App']['FindLocalMessageIDs'](arg1, arg2, arg3);
}

export function FindLocalMessageIDsByLocalID(arg1, arg2, arg3) {
  return window['go']['app']['App']['FindLocalMessageIDsByLocalID'](arg1, arg2, arg3);
}

export function ForceSyncContactSource(arg1) {
  return window['go']['app']['App']['ForceSyncContactSource'](arg1);
}

export function ForceSyncFolder(arg1, arg2) {
  return window['go']['app']['App']['ForceSyncFolder'](arg1, arg2);
}

export function GetAccentBarUnread() {
  return window['go']['app']['App']['GetAccentBarUnread']();
}

export function GetAccount(arg1) {
  return window['go']['app']['App']['GetAccount'](arg1);
}

export function GetAccountFoldersForMapping(arg1) {
  return window['go']['app']['App']['GetAccountFoldersForMapping'](arg1);
}

export function GetAccountProfilePhotos(arg1) {
  return window['go']['app']['App']['GetAccountProfilePhotos'](arg1);
}

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function GetAllAccountIdentities() {
  return window['go']['app']['App']['GetAllAccountIdentities']();
}

export function GetAlwaysLoadImages() {
  return window['go']['app']['App']['GetAlwaysLoadImages']();
}

export function GetAlwaysShowMessageCheckbox() {
  return window['go']['app']['App']['GetAlwaysShowMessageCheckbox']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAttachment(arg1) {
  return window['go']['app']['App']['GetAttachment'](arg1);
}

export function GetAttachments(arg1) {
  return window['go']['app']['App']['GetAttachments'](arg1);
}

export function GetAutoCheckUpdates() {
  return window['go']['app']['App']['GetAutoCheckUpdates']();
}

export function GetAutoDetectedFolders(arg1) {
  return window['go']['app']['App']['GetAutoDetectedFolders'](arg1);
}

export function GetAutostart() {
  return window['go']['app']['App']['GetAutostart']();
}

export function GetComposerFormat() {
  return window['go']['app']['App']['GetComposerFormat']();
}

export function GetComposerMode() {
  return window['go']['app']['App']['GetComposerMode']();
}

export function GetConfiguredOAuthProviders() {
  return window['go']['app']['App']['GetConfiguredOAuthProviders']();
}

export function GetConnectedComposers() {
  return window['go']['app']['App']['GetConnectedComposers']();
}

export function GetContact(arg1) {
  return window['go']['app']['App']['GetContact'](arg1);
}

export function GetContactPhotos(arg1) {
  return window['go']['app']['App']['GetContactPhotos'](arg1);
}

export function GetContactSource(arg1) {
  return window['go']['app']['App']['GetContactSource'](arg1);
}

export function GetContactSourceErrors() {
  return window['go']['app']['App']['GetContactSourceErrors']();
}

export function GetContactSourceStats() {
  return window['go']['app']['App']['GetContactSourceStats']();
}

export function GetContactSources() {
  return window['go']['app']['App']['GetContactSources']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetConversation(arg1, arg2) {
  return window['go']['app']['App']['GetConversation'](arg1, arg2);
}

export function GetConversationCount(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConversationCount'](arg1, arg2, arg3);
}

export function GetConversations(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetConversations'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetCustomOAuthAccounts() {
  return window['go']['app']['App']['GetCustomOAuthAccounts']();
}

export function GetDarkComposerBody() {
  return window['go']['app']['App']['GetDarkComposerBody']();
}

export function GetDarkMailContent() {
  return window['go']['app']['App']['GetDarkMailContent']();
}

export function GetDraft(arg1) {
  return window['go']['app']['App']['GetDraft'](arg1);
}

export function GetDraftForEdit(arg1) {
  return window['go']['app']['App']['GetDraftForEdit'](arg1);
}

export function GetFTSIndexStatus(arg1) {
  return window['go']['app']['App']['GetFTSIndexStatus'](arg1);
}

export function GetFTSIndexStatusAll() {
  return window['go']['app']['App']['GetFTSIndexStatusAll']();
}

export function GetFolderTree(arg1) {
  return window['go']['app']['App']['GetFolderTree'](arg1);
}

export function GetFolders(arg1) {
  return window['go']['app']['App']['GetFolders'](arg1);
}

export function GetIMAPConnectionForUndo(arg1, arg2) {
  return window['go']['app']['App']['GetIMAPConnectionForUndo'](arg1, arg2);
}

export function GetIPCAddress() {
  return window['go']['app']['App']['GetIPCAddress']();
}

export function GetIdentities(arg1) {
  return window['go']['app']['App']['GetIdentities'](arg1);
}

export function GetIdentity(arg1) {
  return window['go']['app']['App']['GetIdentity'](arg1);
}

export function GetImageAllowlist() {
  return window['go']['app']['App']['GetImageAllowlist']();
}

export function GetInlineAttachments(arg1) {
  return window['go']['app']['App']['GetInlineAttachments'](arg1);
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetLastSeenVersion() {
  return window['go']['app']['App']['GetLastSeenVersion']();
}

export function GetLastUpdateCheck() {
  return window['go']['app']['App']['GetLastUpdateCheck']();
}

export function GetLinkedAccountsForContactSync() {
  return window['go']['app']['App']['GetLinkedAccountsForContactSync']();
}

export function GetMailtoMode() {
  return window['go']['app']['App']['GetMailtoMode']();
}

export function GetMarkAsReadDelay() {
  return window['go']['app']['App']['GetMarkAsReadDelay']();
}

export function GetMessage(arg1) {
  return window['go']['app']['App']['GetMessage'](arg1);
}

export function GetMessageCount(arg1, arg2) {
  return window['go']['app']['App']['GetMessageCount'](arg1, arg2);
}

export function GetMessageListDensity() {
  return window['go']['app']['App']['GetMessageListDensity']();
}

export function GetMessageListSortOrder() {
  return window['go']['app']['App']['GetMessageListSortOrder']();
}

export function GetMessageSource(arg1) {
  return window['go']['app']['App']['GetMessageSource'](arg1);
}

export function GetMessages(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetMessages'](arg1, arg2, arg3, arg4);
}

export function GetMicrosoftSharedMailboxes(arg1) {
  return window['go']['app']['App']['GetMicrosoftSharedMailboxes'](arg1);
}

export function GetNativeTitleBar() {
  return window['go']['app']['App']['GetNativeTitleBar']();
}

export function GetOAuthBuildStatus() {
  return window['go']['app']['App']['GetOAuthBuildStatus']();
}

export function GetOAuthCredsChoices(arg1, arg2) {
  return window['go']['app']['App']['GetOAuthCredsChoices'](arg1, arg2);
}

export function GetOAuthCredsStatus(arg1) {
  return window['go']['app']['App']['GetOAuthCredsStatus'](arg1);
}

export function GetOAuthStatus(arg1) {
  return window['go']['app']['App']['GetOAuthStatus'](arg1);
}

export function GetOAuthWarningDisabled() {
  return window['go']['app']['App']['GetOAuthWarningDisabled']();
}

export function GetPGPEncryptPolicy(arg1) {
  return window['go']['app']['App']['GetPGPEncryptPolicy'](arg1);
}

export function GetPGPKeyForEmail(arg1, arg2) {
  return window['go']['app']['App']['GetPGPKeyForEmail'](arg1, arg2);
}

export function GetPGPKeyServers() {
  return window['go']['app']['App']['GetPGPKeyServers']();
}

export function GetPGPSignPolicy(arg1) {
  return window['go']['app']['App']['GetPGPSignPolicy'](arg1);
}

export function GetPendingMailto() {
  return window['go']['app']['App']['GetPendingMailto']();
}

export function GetReadReceiptResponsePolicy() {
  return window['go']['app']['App']['GetReadReceiptResponsePolicy']();
}

export function GetRunBackground() {
  return window['go']['app']['App']['GetRunBackground']();
}

export function GetSMIMECertificateForEmail(arg1, arg2) {
  return window['go']['app']['App']['GetSMIMECertificateForEmail'](arg1, arg2);
}

export function GetSMIMEEncryptPolicy(arg1) {
  return window['go']['app']['App']['GetSMIMEEncryptPolicy'](arg1);
}

export function GetSMIMESignPolicy(arg1) {
  return window['go']['app']['App']['GetSMIMESignPolicy'](arg1);
}

export function GetSearchCount(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetSearchCount'](arg1, arg2, arg3, arg4);
}

export function GetSearchCountUnifiedFolder(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSearchCountUnifiedFolder'](arg1, arg2, arg3);
}

export function GetSearchCountUnifiedInbox(arg1, arg2) {
  return window['go']['app']['App']['GetSearchCountUnifiedInbox'](arg1, arg2);
}

export function GetSenderLogos(arg1) {
  return window['go']['app']['App']['GetSenderLogos'](arg1);
}

export function GetShowMessageListCircles() {
  return window['go']['app']['App']['GetShowMessageListCircles']();
}

export function GetShowMessageListProfilePics() {
  return window['go']['app']['App']['GetShowMessageListProfilePics']();
}

export function GetShowTitleBar() {
  return window['go']['app']['App']['GetShowTitleBar']();
}

export function GetShowViewerCircles() {
  return window['go']['app']['App']['GetShowViewerCircles']();
}

export function GetSkippedUpdateVersion() {
  return window['go']['app']['App']['GetSkippedUpdateVersion']();
}

export function GetSourceAddressbooks(arg1) {
  return window['go']['app']['App']['GetSourceAddressbooks'](arg1);
}

export function GetSpecialFolder(arg1, arg2) {
  return window['go']['app']['App']['GetSpecialFolder'](arg1, arg2);
}

export function GetSpellcheckCustomWords() {
  return window['go']['app']['App']['GetSpellcheckCustomWords']();
}

export function GetSpellcheckEnabled() {
  return window['go']['app']['App']['GetSpellcheckEnabled']();
}

export function GetSpellcheckLanguages() {
  return window['go']['app']['App']['GetSpellcheckLanguages']();
}

export function GetStartHidden() {
  return window['go']['app']['App']['GetStartHidden']();
}

export function GetStartHiddenActive() {
  return window['go']['app']['App']['GetStartHiddenActive']();
}

export function GetSystemTheme() {
  return window['go']['app']['App']['GetSystemTheme']();
}

export function GetTermsAccepted() {
  return window['go']['app']['App']['GetTermsAccepted']();
}

export function GetThemeMode() {
  return window['go']['app']['App']['GetThemeMode']();
}

export function GetTrustedCertificates(arg1) {
  return window['go']['app']['App']['GetTrustedCertificates'](arg1);
}

export function GetUIState() {
  return window['go']['app']['App']['GetUIState']();
}

export function GetUndoDescription() {
  return window['go']['app']['App']['GetUndoDescription']();
}

export function GetUnifiedFolderConversations(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetUnifiedFolderConversations'](arg1, arg2, arg3, arg4, arg5);
}

export function GetUnifiedFolderCount(arg1, arg2) {
  return window['go']['app']['App']['GetUnifiedFolderCount'](arg1, arg2);
}

export function GetUnifiedInboxConversations(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetUnifiedInboxConversations'](arg1, arg2, arg3, arg4);
}

export function GetUnifiedInboxCount(arg1) {
  return window['go']['app']['App']['GetUnifiedInboxCount'](arg1);
}

export function GetUnifiedInboxUnreadCount() {
  return window['go']['app']['App']['GetUnifiedInboxUnreadCount']();
}

export function GetWindowDecorationStatus() {
  return window['go']['app']['App']['GetWindowDecorationStatus']();
}

export function HasPGPKey(arg1) {
  return window['go']['app']['App']['HasPGPKey'](arg1);
}

export function HasSMIMECertificate(arg1) {
  return window['go']['app']['App']['HasSMIMECertificate'](arg1);
}

export function IMAPSearchFolder(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['IMAPSearchFolder'](arg1, arg2, arg3, arg4);
}

export function IMAPSearchUnifiedInbox(arg1, arg2) {
  return window['go']['app']['App']['IMAPSearchUnifiedInbox'](arg1, arg2);
}

export function IgnoreReadReceipt(arg1, arg2) {
  return window['go']['app']['App']['IgnoreReadReceipt'](arg1, arg2);
}

export function ImportPGPKeyFromPath(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportPGPKeyFromPath'](arg1, arg2, arg3);
}

export function ImportRecipientCert(arg1, arg2) {
  return window['go']['app']['App']['ImportRecipientCert'](arg1, arg2);
}

export function ImportRecipientPGPKey(arg1, arg2) {
  return window['go']['app']['App']['ImportRecipientPGPKey'](arg1, arg2);
}

export function ImportSMIMECertificateFromPath(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportSMIMECertificateFromPath'](arg1, arg2, arg3);
}

export function ImportSMIMECertificateFromPathBER(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportSMIMECertificateFromPathBER'](arg1, arg2, arg3);
}

export function InitiateShutdown() {
  return window['go']['app']['App']['InitiateShutdown']();
}

export function IsExtensionEnabled(arg1) {
  return window['go']['app']['App']['IsExtensionEnabled'](arg1);
}

export function IsFTSIndexComplete(arg1) {
  return window['go']['app']['App']['IsFTSIndexComplete'](arg1);
}

export function IsFTSIndexing() {
  return window['go']['app']['App']['IsFTSIndexing']();
}

export function IsFlatpak() {
  return window['go']['app']['App']['IsFlatpak']();
}

export function IsImageAllowed(arg1) {
  return window['go']['app']['App']['IsImageAllowed'](arg1);
}

export function IsOAuthConfigured(arg1) {
  return window['go']['app']['App']['IsOAuthConfigured'](arg1);
}

export function IsReady() {
  return window['go']['app']['App']['IsReady']();
}

export function LinkAccountContactSource(arg1, arg2, arg3) {
  return window['go']['app']['App']['LinkAccountContactSource'](arg1, arg2, arg3);
}

export function ListAccountSetupHooksForProvider(arg1) {
  return window['go']['app']['App']['ListAccountSetupHooksForProvider'](arg1);
}

export function ListAuthContextsForProvider(arg1) {
  return window['go']['app']['App']['ListAuthContextsForProvider'](arg1);
}

export function ListContacts(arg1) {
  return window['go']['app']['App']['ListContacts'](arg1);
}

export function ListDrafts(arg1) {
  return window['go']['app']['App']['ListDrafts'](arg1);
}

export function ListEnabledExtensions() {
  return window['go']['app']['App']['ListEnabledExtensions']();
}

export function ListExtensionRailTabs() {
  return window['go']['app']['App']['ListExtensionRailTabs']();
}

export function ListExtensions() {
  return window['go']['app']['App']['ListExtensions']();
}

export function ListPGPKeys(arg1) {
  return window['go']['app']['App']['ListPGPKeys'](arg1);
}

export function ListPGPSenderKeys() {
  return window['go']['app']['App']['ListPGPSenderKeys']();
}

export function ListSMIMECertificates(arg1) {
  return window['go']['app']['App']['ListSMIMECertificates'](arg1);
}

export function ListSenderCerts() {
  return window['go']['app']['App']['ListSenderCerts']();
}

export function LogFrontend(arg1, arg2) {
  return window['go']['app']['App']['LogFrontend'](arg1, arg2);
}

export function LookupHKP(arg1) {
  return window['go']['app']['App']['LookupHKP'](arg1);
}

export function LookupPGPKey(arg1) {
  return window['go']['app']['App']['LookupPGPKey'](arg1);
}

export function LookupWKD(arg1) {
  return window['go']['app']['App']['LookupWKD'](arg1);
}

export function MarkAllFolderMessagesAsRead(arg1) {
  return window['go']['app']['App']['MarkAllFolderMessagesAsRead'](arg1);
}

export function MarkAllFolderMessagesAsUnread(arg1) {
  return window['go']['app']['App']['MarkAllFolderMessagesAsUnread'](arg1);
}

export function MarkAsNotSpam(arg1) {
  return window['go']['app']['App']['MarkAsNotSpam'](arg1);
}

export function MarkAsNotSpamWithUndo(arg1) {
  return window['go']['app']['App']['MarkAsNotSpamWithUndo'](arg1);
}

export function MarkAsRead(arg1) {
  return window['go']['app']['App']['MarkAsRead'](arg1);
}

export function MarkAsSpam(arg1) {
  return window['go']['app']['App']['MarkAsSpam'](arg1);
}

export function MarkAsSpamWithUndo(arg1) {
  return window['go']['app']['App']['MarkAsSpamWithUndo'](arg1);
}

export function MarkAsUnread(arg1) {
  return window['go']['app']['App']['MarkAsUnread'](arg1);
}

export function MoveLocalMessages(arg1, arg2) {
  return window['go']['app']['App']['MoveLocalMessages'](arg1, arg2);
}

export function MoveMessagesToFolder(arg1, arg2) {
  return window['go']['app']['App']['MoveMessagesToFolder'](arg1, arg2);
}

export function MoveToFolder(arg1, arg2) {
  return window['go']['app']['App']['MoveToFolder'](arg1, arg2);
}

export function MoveToFolderWithUndo(arg1, arg2) {
  return window['go']['app']['App']['MoveToFolderWithUndo'](arg1, arg2);
}

export function MoveToInbox(arg1) {
  return window['go']['app']['App']['MoveToInbox'](arg1);
}

export function MoveToInboxWithUndo(arg1) {
  return window['go']['app']['App']['MoveToInboxWithUndo'](arg1);
}

export function NotifyStartupComplete() {
  return window['go']['app']['App']['NotifyStartupComplete']();
}

export function OpenAttachment(arg1) {
  return window['go']['app']['App']['OpenAttachment'](arg1);
}

export function OpenComposerWindow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['OpenComposerWindow'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenEncryptedAttachment(arg1, arg2) {
  return window['go']['app']['App']['OpenEncryptedAttachment'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['app']['App']['OpenURL'](arg1);
}

export function PickAttachmentFiles() {
  return window['go']['app']['App']['PickAttachmentFiles']();
}

export function PickPGPKeyFile() {
  return window['go']['app']['App']['PickPGPKeyFile']();
}

export function PickRecipientCertFile() {
  return window['go']['app']['App']['PickRecipientCertFile']();
}

export function PickRecipientPGPKeyFile() {
  return window['go']['app']['App']['PickRecipientPGPKeyFile']();
}

export function PickSMIMECertificateFile() {
  return window['go']['app']['App']['PickSMIMECertificateFile']();
}

export function Preflight() {
  return window['go']['app']['App']['Preflight']();
}

export function PrepareReply(arg1, arg2) {
  return window['go']['app']['App']['PrepareReply'](arg1, arg2);
}

export function ProcessPGPMessage(arg1) {
  return window['go']['app']['App']['ProcessPGPMessage'](arg1);
}

export function ProcessSMIMEMessage(arg1) {
  return window['go']['app']['App']['ProcessSMIMEMessage'](arg1);
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function ReadFileAsAttachment(arg1) {
  return window['go']['app']['App']['ReadFileAsAttachment'](arg1);
}

export function ReauthorizeAccount(arg1) {
  return window['go']['app']['App']['ReauthorizeAccount'](arg1);
}

export function ReauthorizeContactSource(arg1) {
  return window['go']['app']['App']['ReauthorizeContactSource'](arg1);
}

export function RebuildFTSIndex(arg1) {
  return window['go']['app']['App']['RebuildFTSIndex'](arg1);
}

export function RefreshWindowConstraints() {
  return window['go']['app']['App']['RefreshWindowConstraints']();
}

export function RemoveAccount(arg1) {
  return window['go']['app']['App']['RemoveAccount'](arg1);
}

export function RemoveFromInbox(arg1) {
  return window['go']['app']['App']['RemoveFromInbox'](arg1);
}

export function RemoveFromInboxWithUndo(arg1) {
  return window['go']['app']['App']['RemoveFromInboxWithUndo'](arg1);
}

export function RemoveImageAllowlist(arg1) {
  return window['go']['app']['App']['RemoveImageAllowlist'](arg1);
}

export function RemovePGPKeyServer(arg1) {
  return window['go']['app']['App']['RemovePGPKeyServer'](arg1);
}

export function RemoveSpellcheckCustomWord(arg1) {
  return window['go']['app']['App']['RemoveSpellcheckCustomWord'](arg1);
}

export function RemoveTrustedCertificate(arg1) {
  return window['go']['app']['App']['RemoveTrustedCertificate'](arg1);
}

export function ReorderAccounts(arg1) {
  return window['go']['app']['App']['ReorderAccounts'](arg1);
}

export function SaveAllAttachments(arg1) {
  return window['go']['app']['App']['SaveAllAttachments'](arg1);
}

export function SaveAllEncryptedAttachments(arg1) {
  return window['go']['app']['App']['SaveAllEncryptedAttachments'](arg1);
}

export function SaveAttachmentAs(arg1) {
  return window['go']['app']['App']['SaveAttachmentAs'](arg1);
}

export function SaveDraft(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveDraft'](arg1, arg2, arg3);
}

export function SaveEncryptedAttachmentAs(arg1, arg2) {
  return window['go']['app']['App']['SaveEncryptedAttachmentAs'](arg1, arg2);
}

export function SavePendingOAuthTokens(arg1) {
  return window['go']['app']['App']['SavePendingOAuthTokens'](arg1);
}

export function SaveUIState(arg1) {
  return window['go']['app']['App']['SaveUIState'](arg1);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['App']['SearchContacts'](arg1, arg2);
}

export function SearchConversations(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SearchConversations'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchUnifiedFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SearchUnifiedFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchUnifiedInbox(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SearchUnifiedInbox'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2);
}

export function SendReadReceipt(arg1, arg2) {
  return window['go']['app']['App']['SendReadReceipt'](arg1, arg2);
}

export function SetAccentBarUnread(arg1) {
  return window['go']['app']['App']['SetAccentBarUnread'](arg1);
}

export function SetAccountEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetAccountEnabled'](arg1, arg2);
}

export function SetAddressbookEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetAddressbookEnabled'](arg1, arg2);
}

export function SetAlwaysLoadImages(arg1) {
  return window['go']['app']['App']['SetAlwaysLoadImages'](arg1);
}

export function SetAlwaysShowMessageCheckbox(arg1) {
  return window['go']['app']['App']['SetAlwaysShowMessageCheckbox'](arg1);
}

export function SetAutoCheckUpdates(arg1) {
  return window['go']['app']['App']['SetAutoCheckUpdates'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['app']['App']['SetAutostart'](arg1);
}

export function SetComposerFormat(arg1) {
  return window['go']['app']['App']['SetComposerFormat'](arg1);
}

export function SetComposerMode(arg1) {
  return window['go']['app']['App']['SetComposerMode'](arg1);
}

export function SetContactSourceWritable(arg1, arg2) {
  return window['go']['app']['App']['SetContactSourceWritable'](arg1, arg2);
}

export function SetDarkComposerBody(arg1) {
  return window['go']['app']['App']['SetDarkComposerBody'](arg1);
}

export function SetDarkMailContent(arg1) {
  return window['go']['app']['App']['SetDarkMailContent'](arg1);
}

export function SetDefaultIdentity(arg1, arg2) {
  return window['go']['app']['App']['SetDefaultIdentity'](arg1, arg2);
}

export function SetDefaultPGPKey(arg1, arg2) {
  return window['go']['app']['App']['SetDefaultPGPKey'](arg1, arg2);
}

export function SetDefaultSMIMECertificate(arg1, arg2) {
  return window['go']['app']['App']['SetDefaultSMIMECertificate'](arg1, arg2);
}

export function SetExtensionEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetExtensionEnabled'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetLastSeenVersion(arg1) {
  return window['go']['app']['App']['SetLastSeenVersion'](arg1);
}

export function SetLastUpdateCheck(arg1) {
  return window['go']['app']['App']['SetLastUpdateCheck'](arg1);
}

export function SetMailtoMode(arg1) {
  return window['go']['app']['App']['SetMailtoMode'](arg1);
}

export function SetMarkAsReadDelay(arg1) {
  return window['go']['app']['App']['SetMarkAsReadDelay'](arg1);
}

export function SetMessageListDensity(arg1) {
  return window['go']['app']['App']['SetMessageListDensity'](arg1);
}

export function SetMessageListSortOrder(arg1) {
  return window['go']['app']['App']['SetMessageListSortOrder'](arg1);
}

export function SetNativeTitleBar(arg1) {
  return window['go']['app']['App']['SetNativeTitleBar'](arg1);
}

export function SetOAuthCreds(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetOAuthCreds'](arg1, arg2, arg3);
}

export function SetOAuthCredsChoice(arg1, arg2) {
  return window['go']['app']['App']['SetOAuthCredsChoice'](arg1, arg2);
}

export function SetOAuthWarningDisabled(arg1) {
  return window['go']['app']['App']['SetOAuthWarningDisabled'](arg1);
}

export function SetPGPEncryptPolicy(arg1, arg2) {
  return window['go']['app']['App']['SetPGPEncryptPolicy'](arg1, arg2);
}

export function SetPGPSignPolicy(arg1, arg2) {
  return window['go']['app']['App']['SetPGPSignPolicy'](arg1, arg2);
}

export function SetReadReceiptResponsePolicy(arg1) {
  return window['go']['app']['App']['SetReadReceiptResponsePolicy'](arg1);
}

export function SetRunBackground(arg1) {
  return window['go']['app']['App']['SetRunBackground'](arg1);
}

export function SetSMIMEEncryptPolicy(arg1, arg2) {
  return window['go']['app']['App']['SetSMIMEEncryptPolicy'](arg1, arg2);
}

export function SetSMIMESignPolicy(arg1, arg2) {
  return window['go']['app']['App']['SetSMIMESignPolicy'](arg1, arg2);
}

export function SetShowMessageListCircles(arg1) {
  return window['go']['app']['App']['SetShowMessageListCircles'](arg1);
}

export function SetShowMessageListProfilePics(arg1) {
  return window['go']['app']['App']['SetShowMessageListProfilePics'](arg1);
}

export function SetShowTitleBar(arg1) {
  return window['go']['app']['App']['SetShowTitleBar'](arg1);
}

export function SetShowViewerCircles(arg1) {
  return window['go']['app']['App']['SetShowViewerCircles'](arg1);
}

export function SetSkippedUpdateVersion(arg1) {
  return window['go']['app']['App']['SetSkippedUpdateVersion'](arg1);
}

export function SetSpellcheckEnabled(arg1) {
  return window['go']['app']['App']['SetSpellcheckEnabled'](arg1);
}

export function SetSpellcheckLanguages(arg1) {
  return window['go']['app']['App']['SetSpellcheckLanguages'](arg1);
}

export function SetStartHidden(arg1) {
  return window['go']['app']['App']['SetStartHidden'](arg1);
}

export function SetTermsAccepted(arg1) {
  return window['go']['app']['App']['SetTermsAccepted'](arg1);
}

export function SetThemeMode(arg1) {
  return window['go']['app']['App']['SetThemeMode'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function Star(arg1) {
  return window['go']['app']['App']['Star'](arg1);
}

export function StartContactsOnlyOAuthFlow(arg1) {
  return window['go']['app']['App']['StartContactsOnlyOAuthFlow'](arg1);
}

export function StartCustomOAuthFlow(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StartCustomOAuthFlow'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartOAuthFlow(arg1) {
  return window['go']['app']['App']['StartOAuthFlow'](arg1);
}

export function SubscribeAllFolders(arg1) {
  return window['go']['app']['App']['SubscribeAllFolders'](arg1);
}

export function SubscribeFolder(arg1, arg2) {
  return window['go']['app']['App']['SubscribeFolder'](arg1, arg2);
}

export function SyncAccountComplete(arg1) {
  return window['go']['app']['App']['SyncAccountComplete'](arg1);
}

export function SyncAllComplete() {
  return window['go']['app']['App']['SyncAllComplete']();
}

export function SyncAllContactSources() {
  return window['go']['app']['App']['SyncAllContactSources']();
}

export function SyncContactSource(arg1) {
  return window['go']['app']['App']['SyncContactSource'](arg1);
}

export function SyncFolder(arg1, arg2) {
  return window['go']['app']['App']['SyncFolder'](arg1, arg2);
}

export function SyncFolders(arg1) {
  return window['go']['app']['App']['SyncFolders'](arg1);
}

export function SyncPendingDrafts(arg1) {
  return window['go']['app']['App']['SyncPendingDrafts'](arg1);
}

export function SyncUnifiedFolder(arg1) {
  return window['go']['app']['App']['SyncUnifiedFolder'](arg1);
}

export function TestCardDAVConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestCardDAVConnection'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function TestOAuthConnection(arg1) {
  return window['go']['app']['App']['TestOAuthConnection'](arg1);
}

export function TestSMTPConnection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['TestSMTPConnection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Trash(arg1) {
  return window['go']['app']['App']['Trash'](arg1);
}

export function TrashWithUndo(arg1) {
  return window['go']['app']['App']['TrashWithUndo'](arg1);
}

export function Undo() {
  return window['go']['app']['App']['Undo']();
}

export function UndoLatestWithResult() {
  return window['go']['app']['App']['UndoLatestWithResult']();
}

export function UndoOperation(arg1) {
  return window['go']['app']['App']['UndoOperation'](arg1);
}

export function Unstar(arg1) {
  return window['go']['app']['App']['Unstar'](arg1);
}

export function UnsubscribeFolder(arg1, arg2) {
  return window['go']['app']['App']['UnsubscribeFolder'](arg1, arg2);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['app']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateContactSource(arg1, arg2) {
  return window['go']['app']['App']['UpdateContactSource'](arg1, arg2);
}

export function UpdateIdentity(arg1, arg2) {
  return window['go']['app']['App']['UpdateIdentity'](arg1, arg2);
}

export function UpdateLocalFlags(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateLocalFlags'](arg1, arg2, arg3);
}
